[package]
name = "rusttut"
version = "0.1.0"
authors = ["Christopher David <chris@arcade.city>"]

[lib]
name = "rusttut"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
jni = { version = "0.5.1", optional = true, default-features = false }

[features]
default = ["jni"]
